### PR TITLE
Add black for formatting + some additional linters

### PR DESCRIPTION
**Pull request by nemacysts**
We don't have any automatically enforced formatting (yapf is optional and not part of our pre-commit), so let's use black since that seems to be what we've settled on.

Additionally, I've added some other "standard" pre-commit hooks (as well as reformatted the pre-commit config file.)

### CODE REVIEW

**Comment by nemacysts** [comment]
files to look at:

(pre-commit config) https://github.com/Yelp/Tron/pull/805/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9 

(tox.ini) https://github.com/Yelp/Tron/pull/805/files?file-filters%5B%5D=.ini&file-filters%5B%5D=.json&file-filters%5B%5D=.py&file-filters%5B%5D=.toml&file-filters%5B%5D=.yapf&file-filters%5B%5D=No+extension#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449

(pyproject.toml) https://github.com/Yelp/Tron/pull/805/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Comment by lanceleih** [comment]
Seems to be failing for me when I run `make test`.
Traceback: https://fluffy.yelpcorp.com/i/9ZHhB7H1zmfGq3bgMzGJBLbMCsxHPHB4.html

stderr:
    ERROR: Package 'pre-commit-hooks' requires a different Python: 3.6.0 not in '>=3.6.1'

**Comment by nemacysts** [comment]
@lanceleih https://github.com/Yelp/Tron/pull/805/commits/c1cad7d28fe683b11e876d140a9aff1a8df621d7 should resolve that until we've finished moving these boxes :)

**Review by lanceleih — APPROVED** [review]
Nice. Passed all tests 👍  This PR LGTM.

**Pull request merged**
