### PR TITLE
Adds Python 3.7; build for Jammy

### PR DESCRIPTION
**Pull request by bobokun**
This reverts PR #879 and fixes dependencies and tests

### CODE REVIEW

**Comment by nemacysts** [comment]
@bobokun any chance you can break this into two commits? one reverting the revert and another fixing tests and whatnot?

**Comment by nemacysts** [comment]
alternatively - another way to approach this is to start from https://github.com/Yelp/Tron/pull/877 -> merge master -> fix tests so that it's easier to review what actually changed vs what was just pre-commit

**Comment by bobokun** [comment]
Yeah good idea. Ill make those changes and split it up for an easier review

**Comment by bobokun** [comment]
Closing in favour for #896

**Pull request closed without merging**
